language: python

install:
  - "sudo apt-get install python3"
  - "pip3 install setuptools numpy sdl2-lib cffi codacy-coverage"
  - "pip3 install -r requirements.txt"

script:
  - "python-codacy-coverage"
  - "prospector"
  - "python3 engine.py"
