language: python
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: required
    env: CC=gcc-8 CXX=g++-8

  fast_finish: true

# sudo is required to prevent xvfb crashes from container-based workers.
sudo: required
dist: trusty
cache: pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libsdl2-dev
services:
  - xvfb

before_install:
- source travis/before_install.sh
- 'wget https://bootstrap.pypa.io/get-pip.py'
- python get-pip.py
- pip install --upgrade setuptools
- pip install --pre --upgrade wheel
- pip install pycparser cffi setuptools pyyaml tcod
before_script:
- pip install --upgrade pytest pytest-cov
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then pip install --upgrade twine; fi
- if [[ -n "$TRAVIS_TAG" && -z "$PYPY3_VERSION" ]]; then pip install --upgrade pyOpenSSL; fi
- pip install codacy-coverage
- coverage xml
- if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then python-codacy-coverage -r coverage.xml || true; fi
