language: python
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: required
    env: CC=gcc-8 CXX=g++-8

  fast_finish: true

# sudo is required to prevent xvfb crashes from container-based workers.
sudo: required
dist: trusty
cache: pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libsdl2-dev
services:
  - xvfb
install:
  - sudo apt-get install g++-8 libsdl2-dev
  - pip install setuptools numpy cffi pyyaml tcod
script:
  - python engine.py
after_success:
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml